[tool.pytest.ini_options]
testpaths = [
    "tests/unit",
    "tests/integration",
    "tests/functional"
]
python_files = ["test_*.py"]
addopts = "-v --cov=app --cov-report=term-missing"
markers = [
    "unit: marks unit tests",
    "integration: marks integration tests",
    "functional: marks functional/API tests",
]
asyncio_mode = "strict"
pythonpath = "."

[tool.ruff]
target-version = "py312"
line-length = 88
extend-exclude = ["migrations", ".venv"]
ignore = ["RUF001"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # Pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C90",  # mccabe complexity
    "PL",   # pylint
    "RUF",  # ruff-specific rules
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
