[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v"  # Remove coverage options from default
pythonpath = "."

[tool.ruff]
target-version = "py312"
line-length = 88
extend-exclude = ["migrations", ".venv"]
ignore = ["RUF001"]  # Ignore Chinese full-width punctuation warnings

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # Pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C90",  # mccabe complexity
    "PL",   # pylint
    "RUF",  # ruff-specific rules
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
