"""Add document table

Revision ID: 6863dabf5089
Revises:
Create Date: 2025-03-01 01:29:52.066411

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6863dabf5089'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'documents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum('PDF', 'WORD', 'TEXT', 'IMAGE', 'MARKDOWN', name='documenttype'),
            nullable=False,
        ),
        sa.Column('doc_metadata', sa.Text(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=True),
        sa.Column('vector_ids', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('analysis_results', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
