name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Add branch detection
    env:
      IS_MAIN: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black isort mypy
        
    # Always run basic checks
    - name: Code formatting check
      run: |
        black . --check
        isort . --check
        
    - name: Type check
      run: |
        PYTHONPATH=$PWD mypy app
        
    - name: Run tests
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test_db
        POSTGRES_SERVER: localhost
      run: |
        pytest --cov=app --cov-report=xml
        
    # Only run additional checks for main branch
    - name: Additional main branch checks
      if: env.IS_MAIN == 'true'
      run: |
        # Add more strict checks here
        pytest --runslow  # Example: run slow tests
        
    - name: Upload coverage
      if: env.IS_MAIN == 'true'  # Only upload coverage for main branch
      uses: codecov/codecov-action@v3
